code/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'events#index'

  match 'signin', to: 'sessions#new', via: :get, as: 'signin'
  match 'auth', to: 'sessions#create', via: [:get, :post], as: 'auth'
  match 'signout', to: 'sessions#destroy', via: :get, as: 'signout'

  resources :users, only: [:index, :update] do
    get 'update_money', to: 'events#new', as: 'update_money'
    resources :events, only: [:create]
  end

  resources :shishas, only: [:new] do
    get 'stop', to: 'shishas#stop', as: 'stop'
    get 'join', to: 'shishas#join', as: 'join'
    get 'leave', to: 'shishas#leave', as: 'leave'
  end

  get 'history', to: 'events#index', as: 'history'

  resources :global_events, only: [:index, :create]
end

code/app/models/user.rb
class User < ApplicationRecord
  has_many :user_shishas, foreign_key: :user_id
  has_many :shishas, through: :user_shishas
  has_one :login_token
  has_many :events

  default_scope { where(allowed: true) }
  scope :super_admins, -> { where(super_admin: true) }
  scope :smoking, -> { joins(:shishas).where('current=1').distinct('user.id') }
  scope :ready, -> { exclude(*smoking.to_a) }
  scope :notified, -> { where(notify: true) }
  scope :debtors, -> { where('money < 0') }
  scope :exclude, ->(*users) { where.not(id: users.map(&:id)) }

  after_create :request_accept_or_promote

  def join_shisha(shisha)
    shisha.user_shishas.create(user_id: id, shisha_id: shisha.id)
  end

  def current_shisha
    shishas.current.first
  end

  def photo_url
    url = read_attribute(:photo_url)
    url ? url : 'dummy-ava.png'
  end

  def update_login_token
    t = login_token
    if t
      t.update_attributes({})
    else
      t = create_login_token
    end
    t
  end

  def action
    @action_controller ||= UserActionController.new(self)
  end

  def draw
    @decorator ||= UserDecorator.new(self)
  end

  def change_money(amount, comment)
    ActiveRecord::Base.transaction do
      self.money += amount
      events.create(change: amount, current: money, comment: comment)
      save
    end
    return unless notify?
    text = "Your money have been changed for *#{amount}*."
    text += "\nComment: _#{comment}_" unless comment.empty?
    text += "\nCurrent: *#{money.round(2)}* RUR"
    message.text = text
    message.send!
  end

  def message
    @message ||= Message.for self
  end

  def self.remind_debtors!
    debtors.each do |debtor|
      title = '*Reminder!*'
      text = "Your account is in debt (*#{debtor.money.round(2)}* RUR). Please, pay off."
      debtor.message.text = title + "\n" + text
      debtor.message.send!
    end
  end

  private

  def should_be_promoted?
    Rails.application.secrets.super_admin_ids.to_a.include? id
  end

  def request_accept_or_promote
    if should_be_promoted?
      update_attributes(allowed: true, super_admin: true)
    else
      request_accept
    end
  end

  def request_accept
    User.super_admins.each do |admin|
      Message.for(admin).accept_user(self).send!
    end
  end
end

code/app/controllers/users_controller.rb
class UsersController < AuthenticatedUserController
  def show
    @user_current_shisha = current_user.current_shisha
    @user_shsihas = current_user.shishas.finished.order(created_at: :desc).eager_load(:users).to_a
  end

  def index
    @users = User.all.order(money: :asc)
  end

  def update
    if current_user.super_admin?
      user = User.find(params[:id])
      user.update_attributes(allowed: user_params[:allowed])
    end
    redirect_to request.referer
  end

  private

  def user_params
    params.permit(:allowed)
  end
end

code/app/views/users/index.html.haml
%table#users-table
  - @users.each do |u|
    %tr
      %td
        = render 'shared/user_panel', user: u, show: [:first_name, :username, :last_name]
      %td
        .money{ class: u.money <= 0 ? 'negative' : '' }= u.money.round(2)
      - if current_user.super_admin?
        %td
          = link_to 'Put money', user_update_money_path(u)
        %td
          = link_to 'Block!', user_path(u, allowed: false), method: :patch, data: { confirm: 'Are you sure?' }

code/app/views/users/show.html.haml
- if @user_current_shisha
  .shisha-list
    = render 'shared/shisha_panel', shisha: @user_current_shisha
- else
  .shisha-list
    - Shisha.joinable.each do |s|
      = render 'shared/shisha_panel', shisha: s
  - if Shisha.available?
    = link_to 'Set up a new shisha!', new_shisha_path, class: 'button create-shisha-button'

.shisha-list
  - @user_shsihas.each do |s|
    = render 'shared/shisha_panel', shisha: s

code/app/views/users/user_not_allowed.html.haml
#user-not-allowed
  = not_allowed_user_message
  = link_to 'Refresh page', root_path, class: 'button'