code/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'events#index'

  match 'signin', to: 'sessions#new', via: :get, as: 'signin'
  match 'auth', to: 'sessions#create', via: [:get, :post], as: 'auth'
  match 'signout', to: 'sessions#destroy', via: :get, as: 'signout'

  resources :users, only: [:index, :update] do
    get 'update_money', to: 'events#new', as: 'update_money'
    resources :events, only: [:create]
  end

  resources :shishas, only: [:new] do
    get 'stop', to: 'shishas#stop', as: 'stop'
    get 'join', to: 'shishas#join', as: 'join'
    get 'leave', to: 'shishas#leave', as: 'leave'
  end

  get 'history', to: 'events#index', as: 'history'

  resources :global_events, only: [:index, :create]
end

code/app/views/shared/_event_panel.html.haml
%table.shisha-panel
  %tr
    %td.date= event.created_at.strftime("%A, %d %B %Y, %H:%M")
    %td.users
      - if event.shisha_id
        - event.shisha.users.each do |u|
          = render 'shared/user_panel', user: u, show: [:first_name]
      - else
        = event.comment
    %td.action
      = event.change.round(2)

code/app/views/shared/_shisha_panel.html.haml
%table.shisha-panel{ class: shisha.current ? 'current' : '' }
  %tr
    %td.date= shisha.created_at.strftime("%A, %d %B %Y, %H:%M")
    %td.users
      - shisha.users.each do |u|
        = render 'shared/user_panel', user: u, show: [:first_name]
    %td.action
      - if shisha.current?
        - if shisha == current_user.current_shisha
          = link_to 'Leave', shisha_leave_path(shisha), class: 'button'
          = link_to 'Stop smoking', shisha_stop_path(shisha), class: 'button'
        - else
          = link_to 'Join!', shisha_join_path(shisha), class: 'button'
      - else
        = "- #{shisha.price.to_f / shisha.users.length}"

code/app/views/shared/_user_panel.html.haml
.user-panel
  = image_tag user.photo_url || asset_path('dummy-ava.png'), class: 'ava', onerror: "this.src='#{asset_path('dummy-ava.png')}'"
  - if user.current_shisha
    = image_tag 'shisha-icon.png', class: 'smoking-badge', title: 'Smoking now'
  %span
    = user.draw.name(show)