code/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'events#index'

  match 'signin', to: 'sessions#new', via: :get, as: 'signin'
  match 'auth', to: 'sessions#create', via: [:get, :post], as: 'auth'
  match 'signout', to: 'sessions#destroy', via: :get, as: 'signout'

  resources :users, only: [:index, :update] do
    get 'update_money', to: 'events#new', as: 'update_money'
    resources :events, only: [:create]
  end

  resources :shishas, only: [:new] do
    get 'stop', to: 'shishas#stop', as: 'stop'
    get 'join', to: 'shishas#join', as: 'join'
    get 'leave', to: 'shishas#leave', as: 'leave'
  end

  get 'history', to: 'events#index', as: 'history'

  resources :global_events, only: [:index, :create]
end

code/app/views/layouts/_navbar.html.haml
#navbar
  = link_to 'Main', root_path, class: 'navitem'
  - if current_user.super_admin?
    = link_to 'Users', users_path, class: 'navitem'
    = link_to 'Main spendings', global_events_path, class: 'navitem'
  = link_to(image_tag('logout-icon.png'), signout_path, class: 'navitem right logout', title: 'Logout') if current_user
  .navitem.right
    = current_user.money.round(2).to_s + ' RUR'
  .navitem.right= current_user.first_name
  = image_tag current_user.photo_url || asset_path('dummy-ava.png'), alt: 'dummy-ava.png', class: 'navitem right ava', onerror: "this.src='#{asset_path('dummy-ava.png')}'"
  - if current_user.current_shisha
    = image_tag 'shisha-icon.png', class: 'navitem right smoking-now-ico', title: 'Smoking now'

code/app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ShishaAccountant
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = favicon_link_tag 'ico.ico'
  %body{ style: 'margin: 0px;' }
    = render 'layouts/navbar' if current_user
    #content= yield